### ISSUE TITLE
A node whose parent is another node is not returned in allLowerNodes

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#11]
When calling nodes.allLowerNodes the nodes grouped under another node are not returned.  The insteon devices that contain multiple nodes can be grouped together by right clicking one and selecting 'Group Devices'

It looks like nodes need to be changed to contain children, but need to look into it deeper.

**Comment by rmkraus** [comment]
You are correct, this isn't supported. I think the best way to do that
would be to put all the modes on the same level. So if parent == node,
parent == parent.parent. That kind of logic

On Thursday, September 3, 2015, jimboca <notifications@github.com> wrote:

> When calling nodes.allLowerNodes the nodes grouped under another node are
> not returned. The insteon devices that contain multiple nodes can be
> grouped together by right clicking one and selecting 'Group Devices'
>
> It looks like nodes need to be changed to contain children, but need to
> look into it deeper.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/automicus/PyISY/issues/11>.
>


-- 
Thanks,

Ryan Kraus

**Comment by shbatm** [comment]
Bumping this.  This should be something we consider fixing in #44 or at least the next version.  I started looking at it.., one idea would be to check nodes for children when parsing through `allLowerNodes` but I think the entire `Nodes` class may need to be looked at to see if there's a better data structure (like a Dict) that can be used.
