### ISSUE TITLE
Issues with KPL Button Nodes

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#110]
For a KPL button like the example xml below

```
<?xml version="1.0" encoding="UTF-8"?>
<nodeInfo>
    <node flag="0" nodeDefId="KeypadButton_ADV">
        <address>46 FD 3F 5</address>
        <name>Family Room Door KPL.C (Tbl)</name>
        <parent type="3">43808</parent>
        <type>1.66.69.0</type>
        <enabled>true</enabled>
        <deviceClass>0</deviceClass>
        <wattage>0</wattage>
        <dcPeriod>0</dcPeriod>
        <startDelay>0</startDelay>
        <endDelay>0</endDelay>
        <pnode>46 FD 3F 1</pnode>
        <property id="ST" value="0" formatted="Off" uom="100" />
    </node>
    <properties>
        <property id="OL" value="" formatted=" " uom="0" />
        <property id="RR" value="" formatted=" " uom="0" />
        <property id="ST" value="0" formatted="Off" uom="100" />
    </properties>
</nodeInfo>
```

Is there a property or method that tells us we can not send a DON

`http://xxx/rest/nodes/46%20FD%203F%205/cmd/DON
`

```
<?xml version="1.0" encoding="UTF-8"?>
<RestResponse succeeded="false">
    <status>404</status>
    <reason code="1" />
</RestResponse>
```

Even the dimmable returns True, but sending a on with value is not acceptable:
`http://xxx/rest/nodes/46%20FD%203F%205/cmd/DON/254
`

```
<?xml version="1.0" encoding="UTF-8"?>
<RestResponse succeeded="false">
    <status>404</status>
    <reason code="1" />
</RestResponse>
```

The only way these can be controlled is to turn on or off a Scene (Group) which the button belongs to.

**Comment by shbatm** [comment]
There is very limited capability detection built into PyISY itself and what is there is not very robust (e.g. dimming/thermostat type detection). For HA, this is all done inside the integration with several different types of sorting and classification that would be difficult to generalize in the PyISY module. I would recommend adding some logic in your integration for it unless you can come up with a silver bullet to implement here.

**Comment by jimboca** [comment]
Thanks, I understand and assumed that would be the answer.  I'll ask Michel if there is an more robust way to handle this.

**Comment by jimboca** [comment]
So the only silver bullet is to download the nodedefs for the devices, but that's a lot of work.

Michel said:
This is how that type is translated:Category(or family).subcategory.version.unused 
So, if you look at the attached, yours is a dimmer(1) while your customer’s is a relay/switch(2). Subcategory is defined in the fam_<cat>.xml. For INSTEON, it’s 1_fam.xml (also attached). This tells you which device it is … this is only good for INSTEON 

The Chris said:
The only real way to do that is to look at the nodedefs for the nodes
https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:V5:Node_Server:Configuration#ISY_Core_Profile_Files

**Comment by jimboca** [comment]
So of course the best way is to download the nodedefs for all nodes, but that's a lot of work...

The main issue I was having is that for KPL's where the main button is dimmable, it was still returning dimmable=True for the sub-buttons, but they are not.  So can add something like:

```
# Matchs KPL buttons except the main one, since that may be dimmable and the others are not.
kpl_sub = re.compile('^[0-9A-F]{2}\s[0-9A-F]{2}\s[0-9A-F]{2}\s[2-9]+')
...
if dimmable and kpl_sub.match(node.address) is not None
    dimmable = False
```

**Comment by shbatm** [comment]
> So of course the best way is to download the nodedefs for all nodes, but that's a lot of work...

This is what I started considering when working on some of the recent updates for async loading, especially as Node Servers become more complex and widespread--since the capabilities vary widely. However, at the moment, I decided my time wasn't best spent in that rabbit hole. 

As mentioned above, I have been trying to avoid managing command validation within PyISY, although long-term it would be nice to just download the device nodedefs and use that to build the valid command structure -- just like the Admin Dashboard does.

> # Matchs KPL buttons except the main one, since that may be dimmable and the others are not.
> kpl_sub = re.compile('^[0-9A-F]{2}\s[0-9A-F]{2}\s[0-9A-F]{2}\s[2-9]+')

The above is probably better done just adjusting the PyISY code from:

```python
        dimmable = (
            "%" in str(self._uom)
            or (isinstance(self._type, str) and self._type.startswith("1."))
            or (
                self._protocol == PROTO_ZWAVE
                and self._zwave_props is not None
                and self._zwave_props.category in ["109", "119", "186"]
            )
        )
```

to:

```python
        dimmable = (
            "%" in str(self._uom)
            or (
                self._protocol == PROTO_INSTEON 
                and self._type.startswith("1.") 
                and self._id.endswith(" 1"))
            or (
                self._protocol == PROTO_ZWAVE
                and self._zwave_props is not None
                and self._zwave_props.category in ["109", "119", "186"]
            )
        )
```

I think only your integration uses the `dimmable` property right now, so I don't see much issue in changing it. As far as I can tell, all Insteon dimmable types are the first sub-node (KPL, FanLinc and all single node switches) -- can you think of any that violate this rule?

Also, if I do a PR for this, do you see any issue with changing the property to `is_dimmable` to coincide with `is_thermostat` and `is_lock`? It would be a breaking change for your code only.

**Comment by jimboca** [comment]
Thanks! Sorry I forgot to get back to this and let you know...
