### ISSUE TITLE
Support controllers and responders.

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#12]
Currently only members are stored which are all contollers and responders.  We need a way to identify them.

The xml looks like:
```
<group flag="132">
<address>30785</address>
<name>Family Room Table</name>
<parent type="3">52063</parent>
<deviceGroup>23</deviceGroup>
<ELK_ID>C02</ELK_ID>
<members>
<link type="16">21 8F 5B 1</link>
<link type="16">1D FF E9 5</link>
<link type="16">1C 46 CB 1</link>
<link type="32">33 1 49 6</link>
<link type="32">2A E 4D 8</link>
</members>
</group>
```

Where 32 is a responder and 16 is a controller.

Ryan requested:

I would prefer to have the members array only be responders and then a new array called controllers be created. Good catch with that. Looking at that type number, I'd bet dollars to donuts that there is also an 8, 4, 2, and 1. They probably then treat those as 6 bit binary flags. So:
100000 - Responder (32)
010000 - Controller (16)
001000 - Something (8)
000100 - Something (4)
000010 - Something (2)
000001 - Something (1)
000000 - ISY System Level Pairing, Not a true Insteon pairing (this is my best guess)

My guess is that they used this design so that nodes could belong to multiple categories. For us, however, I don't think we need to worry about this right now. Let's just make sure that 0, 16, and 32 are handled. I think 0 should be treated like 32 for now.

**Comment by jimboca** [comment]
I'm wondering if the controller info should be also be pushed back to the controlling node, since a node can only control one scene.  For use cases these would seem to make sense because the calling program would likely be interested in what scene the node controls, if any.

**Comment by rmkraus** [comment]
Let's not do that right now. It might be useful, but it would really slow
down boot up times. If a need emerges, then a new method could be
considered.

On Thursday, September 3, 2015, jimboca <notifications@github.com> wrote:

> I'm wondering if the controller info should be also be pushed back to the
> controlling node, since a node can only control one scene. For use cases
> these would seem to make sense because the calling program would likely be
> interested in what scene the node controls, if any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/automicus/PyISY/issues/12#issuecomment-137610815>.
>


-- 
Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
Also, since a controller is also be a responder it seems like should stay in the members list, which is why I originally thought that the members list should just have the type included.

Let me know what you think. I already have the code done to change the members list so it is tuples of nid & type,but I can do it whichever way you prefer.

**Comment by rmkraus** [comment]
That makes sense. Lets have members stay the way it is and add a list called controllers.

**Comment by rmkraus** [comment]
Can this be closed now?
