### ISSUE TITLE
Support for Z-Wave Config Parameters

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#140]
Add support for setting Z-Wave Configuration Parameters. This will be used to support a new service in Home Assistant requested here: https://github.com/shbatm/hacs-isy994/issues/70

Optionally, add support for triggering inclusion/exclusions via REST

>/rest/zwave/node/<nodeAddress>/config/set/<parameterNumber>/<value>/<size>
Set zwave device parameter
The parameter size can be either 1,2, or 4 bytes
/rest/zwave/node/ZW003_1/config/set/1/77/1
/rest/zwave/node/ZW003_1/config/set/2/0xFFFFFFFF/4

Reference: https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:REST_Interface#Z-Wave

CC: @MechEng70

**Comment by shbatm** [comment]
@MechEng70, I'm finally trying to work on this a bit--can you please send me the XML results of the following URL? Doesn't matter which parameter, just need to know the real format that it spits out.

http://your-isy-ip:port/rest/zwave/node/<nodeAddress>/config/query/<parameterNumber>

**Comment by MechEng70** [comment]
Hi! Yes.  I can do it this weekend.  I'm away from my house until tomorrow night.

**Comment by maverick2041** [comment]
I'm happy to help where I can as well.  Here's the output from the path you requested:

<?xml version="1.0" encoding="UTF-8"?><config paramNum="8" size="4" value="33884690" />

**Comment by shbatm** [comment]
Thanks @maverick2041 -- I finally caved and dropped one of my Inovelli Red On/Off switches off my Aeotec stick and put it on the ISY to test. Looks like the draft version linked above is working well. I will push the HACS release as a beta version for you all to try (make sure you enable beta versions for ISY994 in HACS for `v3.0.0.dev17` to show up.

**Comment by maverick2041** [comment]
Thank you @shbatm! - I just tested with v3.0.0.dev18 and it's working perfectly
