### ISSUE TITLE
Ignore state of wireless controllers when determining group (scene) state

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#153]
Wireless controllers are one direction devices that do not wake-up and accept state changes when another controller changes the state of a group. Wireless controllers do not have a local state display, they simply report events.

The unexpected behavior is that groups can remain in the 'on' state when the group is effectively off. The desired behavior is to better reflect the real-world state of the group by ignoring the state of wireless devices.

Devices to consider include: Mini remote, open/close sensor, hidden door sensor, motion sensor, etc based on NodeDefId. (I looked for a list of NodeDefId's to attempt to better define, I didn't locate anything current however)

(Note: at least one other popular/formerly popular 3rd party client seems to treat wireless remotes in the manner described here.)

<sub>Originally opened by @MrBill12 as shbatm/hacs-isy994#80</sub>

**Comment by OverloadUT** [comment]
I fully agree with changing this! The button states have always been confusing.

**Comment by rccoleman** [comment]
Agreed. I have a python_script and set of automations that I use just to 'fix' the state of battery-operated controllers so I get an accurate scene state.

**Comment by shbatm** [comment]
I added a PR which ignores the following NodeDefIDs, which should encompass most battery-powered Insteon devices, but please let me know if you know of any others. In particular--I don't have any Open/Close Sensors so I don't know for sure if that uses one of these NDIDs.

- BinaryAlarm
- BinaryAlarm_ADV
- BinaryControl
- BinaryControl_ADV
- RemoteLinc2
- RemoteLinc2_ADV
