### ISSUE TITLE
SSL failure

### ISSUE THREAD

**Issue by linuxjet** [automicus/PyISY#2]
When connecting to a remote host via https the connection fails.  
one issue related: line 34 of Connection.py. the protocol is the same as standard http - modifying this gets us closer but does not solve the issue.
```
def compileURL(self, path, query=None):
        if self._use_https:
            url = 'https://'
        else:
            url = 'http://'
```

second issue: line 53 of Connection.py the connection is set to verify the ssl cert so no self signed certs will work.  disabling verification allows it to try to connect but with lots of warning about cert security.  
```
try:
            r = requests.get(url, auth=(self._username, self._password),
                    timeout=10,verify=False)
```
```
- this disables the ssl warnings
def request(self, url, ok404=False):
        requests.packages.urllib3.disable_warnings()
```

from here the request goes through, but the connect fails. the connection is left attempting to constantly reconnect.
```
PyISY lost connection to the ISY event stream.
PyISY attempting stream reconnect.
PyISY reconnected to the event stream.
PyISY lost connection to the ISY event stream.
PyISY attempting stream reconnect.
PyISY reconnected to the event stream.
PyISY lost connection to the ISY event stream.
PyISY attempting stream reconnect.
PyISY reconnected to the event stream.
```

**Comment by rmkraus** [comment]
Thank you very much for the detail. Admittedly, HTTPS  hadn't been tested as well as they should have been. Aside from the typo on my end, it looks like verifying certs is a relatively new feature in Python's httplib and I had not debugged against the updated library.

Interestingly enough for me, after making those changes, I cannot connect to the ISY controller at all. The HTTPS server appears to be dropping the connection as soon as it is made. This is true even for the standard REST API calls. For one reason or another, the ISY seems to be dropping Python sockets as soon as they are created.

Would you mind telling me which version of the firmware you are using? I am on v.4.2.30 (newest). I tested on the v.5 alpha and the same problem appears to exist. I am inclined to guess that you are using an older version of the firmware as it appears your REST API calls go through without incident.

**Comment by rmkraus** [comment]
While reviewing change logs for the ISY Firmware, I was quickly reminded that UDI disabled SSL support and now only accepts TLS. Python likes to use SSL unless explicitly told to use TLS. This is most definitely the reason for some of this heartache. I'll be looking into that.

**Comment by linuxjet** [comment]
I am using beta 4.3.30 with tls1.2 set as encryption level.

**Comment by rmkraus** [comment]
Very interesting. I am actually surprised you got as far as you did! I would have expected errors to be thrown indicating that it could not make the initial connection to the controller. Something along these lines:

```
ERROR:PyISY.ISY:ISY Could not recieve response from device because of a network issue.
ERROR:PyISY.ISY:ISY Could not recieve response from device because of a network issue.
ERROR:PyISY.ISY:PyISY could not connect to the ISY controller with the provided attributes.
```

**Comment by rmkraus** [comment]
Just as a heads up, the fix for this will require that the end user has OpenSSL version 1.0.1 or greater. Version 1.0.1g or greater will be recommended since that has the Heartbleed patch. Python must also have been compiled against that library. Python version 2.7.9 or greater or Python 3.4 or greater will also be required. Without these minimum requirements, HTTPS will not be available.

**Comment by rmkraus** [comment]
Alright, the newest version on here now properly supports HTTPS with both TLS 1.1 and 1.2.  I will be running some durability tests on it before publishing it to PyPI. In the meantime, if you clone this repository and place the PyISY directory in your Python Path, you can do some early testing on it. I am not able to test with TLS1.2 as I don't have a Pro ISY. There is very little difference between the two so I don't anticipate any problems. Your command to create the ISY object will now look like this:

``` Python
isy = PyISY.ISY(ADDR, PORT, USER, PASS, use_https=True, tls_ver=1.2)
```

Please let me know if you have any issues. A point to keep in mind is that this version still has no support for Z-Wave.

**Comment by linuxjet** [comment]
tested and working.  thank you.  no issues.

**Comment by rmkraus** [comment]
Left running for about 12 hours with HTTPS with no issues. I'm pushing the updates to PIP now and publishing the updated documentation.
