### ISSUE TITLE
Lock Manager

### ISSUE THREAD

**Issue by MechEng70** [automicus/PyISY#233]
Can you create a way to manager the lock devices?  to include users, codes, schedules, etc.  Most locks are zwave and user rest commands.  Can there be a "isy994.send_lock_command" type of command?

Here is an example of a Zwave Lock Manager for HA: https://community.home-assistant.io/t/zwave-lock-manager-updated/189932

**Comment by shbatm** [comment]
This isn't something that will be included here. The Lock Parameters can be set and retreived with the Z-Wave Parameter Services and if something was going to be built for Home Assistant it would need to be built as a separate add-on. 

Good idea, but trying to keep PyISY just to the core communciation to/from the ISY.
