### ISSUE TITLE
ISY Version 5.06 or greater causing issues?

### ISSUE THREAD

**Issue by ficklma1** [automicus/PyISY#24]
@rmkraus - I just recently went from ISY version 5.04 to 5.08 and getting errors.  Will try to post exact error soon, but wanted to bring attention to possible issue.
Thanks

**Comment by hoopty** [comment]
See #21 they have addressed this there.

**Comment by hoopty** [comment]
@ficklma1 - is this resolved?   If so, can you please close the issue.

**Comment by boojew** [comment]
Fan controls no longer working - component ISY home-assistant/home-assistant#7902 is incorrectly associated with this issues

**Comment by rmkraus** [comment]
Fan controls not working in Home Assistant is an issue with Home Assistant and not PyISY. 
Version 1.0.8 of PyISY should have better support for version 5 firmwares.
