### ISSUE TITLE
Missing Unsubscribe or check for isSubscribed.

### ISSUE THREAD

**Issue by JavierRefuerzo** [automicus/PyISY#244]
Hi Guys,

First please forgive if I misunderstand how the library handles heartbeat  and reconnection events. This library is well written and clean alast, I am not very fluent in Python. Most of what I gathered are from PyISY/ISY logs and previous knowledge of subscription issues created by stress tests and/or debuging clients other than PyISY. 

ISY Issue: 
The Original ISY994 hardware has limited resources. When under heavy load this can lead to heartbeats not reaching clients before 120 seconds.  If a client does not close a socket gracefully and ISY is still under heavy load this may result in a dangled socket on ISY.  If there are too many dangled sockets, manual intervention is needed to close dangled sockets although sometimes reboot is still required.  There may be issues with the return value of the SOAP function Subscribe with a previous subscription SID. However the return values are not well documented, so at this point I must rely on what I've been told.

PyISY Issue:
It appears PyISY gets into a subscription loop with ISY when ISY is under heavy load.  Looking at the source it does not appear that PyISY calls unsubscribe and simply calls socket.close() in the _lost_connection function.   Calling socket.close() without unsubscribing gracefully may lead to dangled sockets in ISY. There is also a SOAP function in PyISY called "Resubscribe", from an ISY standpoint this is not resubscribe, but a new subscribe function which returns a new SID. 

Recommendation:
I spoke with Michael and he is very adamant that libraries should check the SOAP call isSubscribed before disconnecting a reused subscription socket on missed heartbeat.  In apps I've authored I simply call unsubscribe before I force close a socket when a heartbeat is missed.  Mobile user interaction is usually less than 120 seconds, so it may be a good idea to check isSubscribed for long running subscription processes.  As a final note, I have have found that waiting 3 seconds after unsubscribe is called, then attempting a new socket connection works well, this may allow PyISY to reduce the  one minute (?) wait duration.

**Comment by shbatm** [comment]
Thanks for digging in on this. I'll have to look closer when I get a chance, it's been quite a while since I've looked at the SOAP connections. Just FYI, I know there are still a few modules that use V2 of this library, but the Home Assistant connections use the v3.x.x branch and IIRC only use the Websocket connections, not SOAP.

**Comment by shbatm** [comment]
If you or anyone else want to test, it may be worth just changing [this line](https://github.com/automicus/PyISY/blob/master/pyisy/events.py#L217) to `self.unsubscribe()`. The only time that would be an issue and need further handling I can see off the bat is a true socket error (broken pipe/OSError).

**Comment by jimboca** [comment]
Thanks @JavierRefuerzo 
@shbatm I can take a look at it tomorrow and try your suggestion, app the pointer.
I thought the only changes for V3 were to make it async. I will try and move HueEmulator over to V3 when I move it to Polyglot V3.

**Comment by shbatm** [comment]
@jimboca thanks! And also, wow what a f-up on my part... I just went back and looked and the switch to Websockets is not in the release notes for V3 anywhere. 

Yes, a MAJOR part of the switch to Async and increasing stability in v3 was to switch the default to websockets. That was like 70% of the testing and issues in creating v3 and I totally left it out of the notes...

**Comment by JavierRefuerzo** [comment]
Hi @shbatm ,
Thanks. I knew I missing something, although even websocket connections require the SOAP function unsubscribe as I do not believe there is a rest equivalent.

**Comment by jimboca** [comment]
@shbatm I will definitely work on converting to V3 when I move to PG3.  It's a more effort because Polyglot is not async, but I've incorporated a couple other async libraries in other nodeservers so shouldn't be to difficult.

I made the suggested change in a local clone last night, and so far it is looking great, only one subscription currently open for PyISY which is a big improvement.  Will let it run for a few more days to see how it goes.

**Comment by jimboca** [comment]
This looks to be working great!  Same sid for 2 days now.

**Comment by jimboca** [comment]
Still the same sid, I think this is good to release.

**Comment by jimboca** [comment]
@shbatm This has been working great now for over 2 weeks on my system.  Can it be released?

**Comment by shbatm** [comment]
@jimboca - yes, I will try and get it pushed in the next day or so.

**Comment by jimboca** [comment]
Thanks @shbatm !

**Comment by JavierRefuerzo** [comment]
Thanks @shbatm!  Closing reference #245
