### ISSUE TITLE
No Groups show up in nodes due to "ignore controller group"

### ISSUE THREAD

**Issue by OverloadUT** [automicus/PyISY#27]
What is the purpose of this logic?
https://github.com/automicus/PyISY/blob/master/PyISY/Nodes/__init__.py#L168

I was trying to figure out why none of my scenes were showing up as Groups, and finally tracked it down to this issue. Every single one of my scenes has a family of 6, and I can't actually find a description in the ISY documentation that explains what `family` is meant to indicate.

**Comment by jimboca** [comment]
What version​ of isy firmware are you running? This change was made for an issue in 5.x and should have been compatible with older versions, but looks like it's not.

**Comment by jimboca** [comment]
Sorry, the reason it was added was because the ISY (or whatever you name it) was showing up as the first group before any devices so PyISY would crash since the devices in the group didn't exist yet.

**Comment by OverloadUT** [comment]
I am on version 5.0.8

The better way to filter out the root object is to check the `flag` on the group for 0x08, which means `NODE_IS_ROOT`

However, now that I am looking at #21's commits, I can see that this IS how it was implemented. Looks like the check for family == 6 is from a change made 2 years ago to accomplish the same goal.

My recommendation would be to remove the `family == 6` check, since the more recent changes hide the root node using the flag.

**Comment by jimboca** [comment]
Can you give it a try? If not, I can try to look this weekend, if upgrading to 5.0.10 goes smoothly.

**Comment by boojew** [comment]
Fan controls no longer working - component ISY home-assistant/home-assistant#7902 is incorrectly associated with this issues
