### ISSUE TITLE
Owner Change

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#324]
@balloob or @OverloadUT -- As it seems I'm the only person still actively maintaining this repo, would you mind promoting my rights in this Repo/Org? 

I'd like to be able to do some branch cleanup (make 3.x.x > main, depreciate 2.x.x to a separate branch), and enable discussions/projects.

**Comment by balloob** [comment]
Done

**Comment by shbatm** [comment]
Thank you. Much appreciated.
