### ISSUE TITLE
[V3] Discussion: Move to websockets library

### ISSUE THREAD

**Issue by OverloadUT** [automicus/PyISY#53]
I want to use this issue as a discussion thread on the merits and drawbacks of moving this library to use a Websocket library to abstract all of the websocket communication.

Here is one such library that looks pretty decent: https://pypi.org/project/websockets/

It requires Python 3.6, and wouldn't you know it, the next version of Hass will officially raise its minimum Python version to 3.6!

**Comment by jimboca** [comment]
Please remember Hass is not the only place PyISY is used.  It's also used on ISY Polyglot Nodeservers as well, which could move to 3.6 but not there yet.

**Comment by OverloadUT** [comment]
@jimboca Yep, that's one reason I wanted to start a place for discussion. Overall I agree with Home Assistant's approach to minimum Python versions (documented here: https://github.com/home-assistant/architecture/blob/master/adr/0002-minimum-supported-python-version.md )

Keep in mind that we would not be breaking already-shipped versions of PyISY. Under this proposal, it's likely that we would publish a big new version with shbatm's refactor, and then pin that as the last <=3.5 supported version.

But we also shouldn't just move to a library and bump minimum requirements just for the fun of a refactor! But this talk about needing to support chunked encoding for the 5.0 official release made me wonder if that would be the time we should refactor the socket code here to use a library to make it all cleaner...

**Comment by shbatm** [comment]
Sounds like a good path forward to me... I support moving to a more robust websocket package built by people with a better understanding of sockets than us, but I don't want to cause a huge wave of breaking changes for existing integrations until they're ready to make that move.

Re: ISYv5 support -- @jimboca I know Polyglot v2 / PGC uses MQTT to communicate back and forth to the node servers, but does it still use the websocket connections receive updates from the ISY? It'd be nice to fork this off down to the road once Polisy/v5.0 goes mainstream to get the updates from Polyglot but I haven't dug in that far on the ISY<-->Polyglot side to understand if that's feasible (or makes sense at all).

**Comment by OverloadUT** [comment]
> built by people with a better understanding of sockets than us

That's the critical aspect from my perspective. We're in the other thread trying to understand the number of bytes per character and how to check if a socket chunk has been completely read, and it just smacks of "why are you doing this yourself?"

But yeah, breaking compatibility should be done with care, and it should only be done in the context of fixing a bug or adding new support for something. Also, the lib I linked in the OP is just one option :)

**Comment by jimboca** [comment]
> Re: ISYv5 support -- @jimboca I know Polyglot v2 / PGC uses MQTT to communicate back and forth to the node servers, but does it still use the websocket connections receive updates from the ISY? It'd be nice to fork this off down to the road once Polisy/v5.0 goes mainstream to get the updates from Polyglot but I haven't dug in that far on the ISY<-->Polyglot side to understand if that's feasible (or makes sense at all).

@shbatm You are correct that in general Polyglot V2 & PGC do not use PyISY, but some nodeservers like my HueEmulator rely on PyISY socket connection to control the ISY since that can not be done directly thru Polyglot.

**Comment by rmkraus** [comment]
My voice shouldn't be loudest as I'm not even using this right now, but.....

What issue would this change resolve?

On the surface, I'm not opposed to the idea. However, I am 100% opposed to solving problems that don't exist. #51 has been the first issue with the websocket code. It was fixed by porting the newer SSL code to the older plain text code. In the meantime we found another bug (the * 8 issue). Both are fixed in #52 and #44.

**Comment by OverloadUT** [comment]
I completely agree with that question needing a solid answer before anything like this would happen. I wanted to start the discussion so that if in the future when a new feature, protocol change, big bug, or something else like that comes along, moving to a library to address it can be on the table with some thought already put into it.

**Comment by rmkraus** [comment]
![image](https://user-images.githubusercontent.com/4956442/61594825-1a023900-abbe-11e9-9166-cca68c042b21.png)

That library looks good. After some though, I would even support moving to this library once [this guy](https://pythonclock.org/) hits zero. Somewhat contradicting my previous post, moving this library to asyncio would be a great move and this library would simplify that.

**Comment by OverloadUT** [comment]
Yeah, asyncio has been something in the back of my head. Home Assistant now has an [Integration Quality Scale](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html) for components and it's a dream of mine to get the ISY component to Platinum, which requires going completely async.

**Comment by rmkraus** [comment]
I'm all for it. Those are all good guidelines they've put into place. 

My opinion, unless there is a pressing need sooner, let's make that a January project as a farewell salute to Python 2. 🖖 
Around that time, I should be moving into a new house to automate.

@jimboca - Does that timeline work well for your needs?

**Comment by shbatm** [comment]
@overloadut I call "not it" on getting through Gold (web config + discovery), but I have started changing some of the functions to async calls ([isy updates branch](https://github.com/shbatm/home-assistant/tree/isy994-climate/homeassistant/components/isy994))

Just a note: I pulled down my PR from HA for now until the changes here are ready and I can split up those updates to HA. If you have any other changes you want to make on the HA side, I'm happy to help where I can, and that branch has made for a good testing ground as a custom component.

**Comment by shbatm** [comment]
Tacking on -- if we move to a websockets library we should also move to an async library for making the REST requests, for example [aiohttp](https://github.com/aio-libs/aiohttp).

**Comment by shbatm** [comment]
Implemented Websockets in V3. Closing this issue.
