### ISSUE TITLE
Discussion: VarEvents vs. @property.setter Events

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#60]
Just curious what your thoughts are on staying with the VarEvents module for handling updates and events versus simplifying back to just using an @property.setter function to raise events and control updates.

VarEvents is nice, but I keep catching issues where there are type mismatches, or a need to access the underlying private `._val` because the type is not necessarily known. This also requires handlers and exceptions for when something is None or undefined. 

Just wondering if there is a better way to get the advantages from VarEvents without the typing hassles if we move everything to Python 3 for the next version.

**Comment by OverloadUT** [comment]
Personally I am fine either way. I've never really dug into the VarEvents functionality and what it gets us.

**Comment by shbatm** [comment]
I messed around with what it takes to remove the VarEvents dependency today and have a working version for testing with Home Assistant here:
- https://github.com/shbatm/hacs-isy994/tree/PyISY_native_events
- https://github.com/shbatm/PyISY/tree/native_events (requires local install with `pip install -e ./`)

This is built on the current PyISY-beta branch and also removes the Climate module as discussed elsewhere (lumped together because Climate uses a ton of watched variables).

In my opinion, removing VarEvents is in the spirit of simplifying this module. The biggest thing you lose (that I can tell) is that you can't call a non-silent `node.status.update(value)` and have it automatically call the command on the ISY. This functionality was not used in the HA integration, but I don't know how much it is used in other integrations. My thought is that you should be explicitly calling the commands to the ISY (e.g. via the `on()` or `off()` calls), not just updating the value. Again -- this is biased to how HA handles things, not sure about the other integrations.

The "gain" is you don't have to worry as much about the type mismatches and extra dependency. VarEvents Properties re-create/redefine a lot of built-in functions just to maintain operability.  I can definitely see how it can be useful in other integrations, but I think it is now overkill for this module (again--my blunt honest opinion, trying to simplify the integration I'm familiar with, this should not be implemented without considering where else this is used).
 
@jimboca @rmkraus -- Thoughts on this? This change wouldn't be made until a major version bump which would allow existing integrations the ability to pin at v1.x and not lose this functionaility.

**Comment by jimboca** [comment]
VarEvents handles the change notifications, right?  So as long as I can still subscribe to changes then I'm ok with it
```node.status.subscribe('changed', self.get_all_changed)```
I have it on my todo list to convert my hue-emulator Polyglot to your beta branch, but I haven't gotten to it yet.

**Comment by shbatm** [comment]
@jimboca Yes, you still subscribe to the changes. The method changes slightly, but it uses the same structure as the existing `control_events` subscription:

```python
# Old:
node.status.subscribe("changed", self.on_update)
# New:
node.status_events.subscribe(self.on_update)
value = node.status  # Status is now just a property.
```

**Comment by jimboca** [comment]
Then it sounds fine to me.  I only use node.status for checking brightness level.
