### ISSUE TITLE
Connect through ISY Portal

### ISSUE THREAD

**Issue by mkohanim** [automicus/PyISY#82]
Hi shbatm,

Is it possible to use this library against ISY Portal?

Thank you.

**Comment by OverloadUT** [comment]
Currently this module only supports talking to the ISY directly. I am not aware of any plans or requests to have it go through the ISY Portal yet.

The main (but not only) users of this module is Home Assistant, and in Home Assistant there is a very large focus on maximizing local communication whenever possible to keep dependencies off of the cloud, so I would be surprised to see anyone asking for ISY Portal support from that community.

I am very curious why you ask! Is it something you'd like to see?

**Comment by mkohanim** [comment]
Hi OverloadUT,
Yes. The reason is that the only difference is the host:port, the base url, and username/pwd. Everything else identical to connecting to ISY directly.

**Comment by OverloadUT** [comment]
Ah! Well in that case I don't see any reason it wouldn't work! We're certainly not doing anything on purpose to prevent it. It's something we ought to test to confirm!

**Comment by mkohanim** [comment]
That would be great Greg. Do you have an ISY Portal account?

**Comment by OverloadUT** [comment]
I've got an account (same user as here, but @gmail), but the license is expired at the moment. I need to go upgrade my ISY firmware as well, which has been on my to-do list for a while :)

**Comment by mkohanim** [comment]
Please send me your uuid and I will extend it for you and anyone else who can fix this issue.

**Comment by jimboca** [comment]
This is now working, the user didn't have the preferred ISY set.

**Comment by mkohanim** [comment]
This is excellent news! Thanks so much.

**Comment by arrowstem** [comment]
Hello, just to add more details, I was the guy who tried (and couldn't) connect to ISY portal using PyISY code 

isy = PyISY.ISY(ADDR, PORT, USER, PASS, HTTPS)

with proper arguments passed to it. As it turned out, the reason it failed to connect was that I didn't have a preferred ISY set (even though I only have a single ISY under my username, so I'd think it would be my preferred ISY by default). 

While I was trying to figure out why PyISY.ISY(...) was not successful, I found the exception that was raised in the file connection.py, line 48:

                raise(ValueError('PyISY could not connect to the ISY '
                                 + 'controller with the provided attributes.'))

So I thought one of the arguments (ADDR, PORT, USER, PASS, HTTPS) was incorrect. Actually the reason was that preferred ISY was not set. By contrast, when opened the link https://my.isy.io/rest/status in a web browser, the page showed a clear error message saying "Preferred ISY not set on user profile". It would be nice if PyISY also provided a correct error message in this case. 

On the other subject, I really want to connect to ISY portal rather than ISY itself because I need to make that connection from a remote server, and I am comfortable doing that from a Python script. So I thought PyISY would be ideal for my goals. Thanks for developing this module!

**Comment by shbatm** [comment]
@mkohanim - just thinking about future use cases for this: is there anything in the Portal REST protocol for determining which ISY to use?

I'm thinking about if someone has multiple ISYs tied to a single portal account, how would this module be able to differentiate between them?

**Comment by shbatm** [comment]
> By contrast, when opened the link https://my.isy.io/rest/status in a web browser, the page showed a clear error message saying "Preferred ISY not set on user profile".

@arrowstem glad you got it working. I'll look at the error message... Right now the module tests the connection by calling an invalid REST URL ('/rest/ping`) just to see if it gets a 404 error (valid connection, invalid url) or something else. It should probably call (`/rest/status`) to provide some more useful info (@OverloadUT, one of the last 2 PRs includes a change to allow connection testing without downloading the full config, this would probably fit well there).

**Comment by jimboca** [comment]
> @mkohanim - just thinking about future use cases for this: is there anything in the Portal REST protocol for determining which ISY to use?
> 
> I'm thinking about if someone has multiple ISYs tied to a single portal account, how would this module be able to differentiate between them?

Currently this is based on the login credentials, different user (email) for each preferred ISY, and if you don't want a unique email you can use to + like username+somestring@gmail.com for each one.

**Comment by mkohanim** [comment]
@shbatm , thanks so very much! Please note that the only reason you need Preferred ISY is for cases (such as MobiLinc and apparently PyISY), where you do NOT define the base URL during the connection. Each ISY has a full path in ISY Portal. So, if you allow the based URL path to be defined during connection (instead of /rest/ping), then the only failure would be authentication. So, my.isy.io:443, username, pwd, https=true, baseURL = <whatever is the URL for ISY in the Portal>/rest/<whatever>.

**Comment by shbatm** [comment]
@mkohanim Thanks for the suggestion. Added a `webroot` parameter to some upcoming connection changes for V2. Connection details will be:

```python
isy = ISY(
    address="my.isy.io",
    port=443,
    username="your@portal.email",
    password="yourpassword",
    use_https=True,
    tls_ver=1.1,
    log=None,
    webroot="/isy/unique_isy_url_code_from_portal",
)
# Unique URL can be found in ISY Portal under 
#   Tools > Information > ISY Information
#  Do not add /rest/ to the end!
```

**Comment by shbatm** [comment]
Still having issues connecting to the event stream over the portal. What is the subscription endpoint? Is it `/isy/<<myisyaddr>>/services` or something different?

**Comment by mkohanim** [comment]
@shbatm , websockets don't work on the Portal. If you are not using websockets, then the URL and everything else should be identical to how you do it on ISY (with the exception of webroot).

**Comment by shbatm** [comment]
I got it working -- PyISY still uses SOAP for the event stream, but it looks like there were some format updates needed to the connection content. The ISY itself seems tolerant to the formatting differences, but the Portal is not. 

@arrowstem - This should be working now in `pyisy-beta=2.0.0.dev151`.

@OverloadUT - I've got the changes staged for one of the next PRs you'll see for V2. I had already made some changes to allow connection testing without requesting and downloading all of the REST endpoints.

**Comment by mkohanim** [comment]
@shbatm , this is wonderful news. Thanks SO very much.

**Comment by arrowstem** [comment]
@shbatm , thank you for the update. I installed pyisy-beta=2.0.0.dev151 but now I have another issue with my code. I must mention that I'm using Python 3.7 with Anaconda under Win10. Hope this configuration is supported. My code:

```
import pyisy
[constants are defined here]
isy_conn = pyisy.ISY(ADDR, PORT, USER, PASS, HTTPS)
```

which worked before (up to pyisy-beta=2.0.0.dev146), now produces an error:

Traceback (most recent call last):

  File "[...]\isy_interface.py", line 46, in <module>
    isy_conn = pyisy.ISY(ADDR, PORT, USER, PASS, HTTPS)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\isy.py", line 89, in __init__
    self.programs = Programs(self, xml=self.conn.get_programs())

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 95, in __init__
    self.parse(xml)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 260, in parse
    pobj = Program(self, address, pname, **data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\program.py", line 75, in __init__
    super(Program, self).__init__(programs, address, pname, pstatus)

TypeError: super(type, obj): obj must be an instance or subtype of type

Any idea what's wrong?

**Comment by arrowstem** [comment]
To double-check it under a different environment, I made a clean installation of pyisy-beta-2.0.0.dev151 on a Linux server and ran the same test code. Here's the error I've got (a different one, as it seems):

```
Traceback (most recent call last):
  File "isy_test.py", line 1, in <module>
    import pyisy
  File "/home/ubuntu/optimizer/flask/lib/python3.5/site-packages/pyisy/__init__.py", line 26, in <module>
    from .isy import ISY
  File "/home/ubuntu/optimizer/flask/lib/python3.5/site-packages/pyisy/isy.py", line 5, in <module>
    from .climate import Climate
  File "/home/ubuntu/optimizer/flask/lib/python3.5/site-packages/pyisy/climate.py", line 8, in <module>
    from .helpers import value_from_xml
  File "/home/ubuntu/optimizer/flask/lib/python3.5/site-packages/pyisy/helpers.py", line 194
    f"NodeProperty('{self.control}': value='{self.value}' "
                                                          ^
SyntaxError: invalid syntax
```

**Comment by shbatm** [comment]
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\program.py", line 75, in __init__
>     super(Program, self).__init__(programs, address, pname, pstatus)

I'm wondering if this has to do with Linux vs Windows python: please try changing `super(Program, self).__init__(` to this: `super().__init__(` on Line 75 of 
`"C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\program.py"`.

Let me know if that fixes it an I'll make the change.

> To double-check it under a different environment

What version of python did you run this 2nd test on? Looks like it may be something < Python 3.6.

**Comment by arrowstem** [comment]
Yes, it's Python 3.5 under ubuntu. Should I upgrade it to 3.7?

**Comment by shbatm** [comment]
@arrowstem yes, at least to 3.6. The `f`-strings weren't introduced until 3.6.

Let me know if the other change fixes the issue on windows.

**Comment by arrowstem** [comment]
I did change the code to super().__init__(...) on Line 75 of program.py and ran it under Windows, here's what I've got:

```
Traceback (most recent call last):

  File "[path]\isy_interface.py", line 46, in <module>
    isy_conn = pyisy.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,log)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\isy.py", line 81, in __init__
    self.programs = Programs(self, xml=self.conn.get_programs())

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 95, in __init__
    self.parse(xml)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 260, in parse
    pobj = Program(self, address, pname, **data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\program.py", line 75, in __init__
    super().__init__(programs, address, pname, pstatus)

TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by shbatm** [comment]
Strange, something is not loading correctly when it's trying to get your list of programs. 

Would you mind: 
1) Creating a separate issue for this on my [beta branch](https://github.com/shbatm/PyISY/issues) since it's broken on the beta version and not related to this original issue. 
2) Post there, Slack DM, or e-mail me your `programs.xml` file (https://my.isy.io/rest/programs?subfolders=true) -- it shouldn't have anything sensitive in it, but please double check.
3) Are you sure this worked on `2.0.0.dev146`, or did you mean it stopped working when you tried to switch from V1 to V2?
