### ISSUE TITLE
poorly formatted XML error

### ISSUE THREAD

**Issue by arrowstem** [automicus/PyISY#83]
I'm running PyISY's current version (1.1.2) under Ubuntu in a simple test code:
```
isy_conn = PyISY.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,log)
```
It prints:
```
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1
ISY Could not parse variables, poorly formatted XML.
```
Could you advise where I should look for that XML at ISY Portal - or elsewhere?

**Comment by shbatm** [comment]
That's a valid URL (try pasting `https://my.isy.io:443/rest/vars/definitions/1` in your browser and logging in with your Portal login), but do you have any integer variables defined in your ISY? That's been an issue before (although it was with the NodeJS version) if you don't have at least 1 variable defined of each type.

If you can access that page, paste the results here.
