### ISSUE TITLE
Add support for ISY Device notes and spoken properties

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#9]
Would you be ok with loading the ISY notes and spoken properties so caller can reference nodes thru the spoken name?  More info is here:  http://forum.universal-devices.com/topic/16646-notes-field/?p=146578

This would make it easier to reference the spoken name for my Amazon Echo interface in https://github.com/jimboca/ISYHelper

Thanks,
Jim

**Comment by rmkraus** [comment]
I am not opposed to that. I haven't used those features before but it
should be easy enough to integrate. I don't have time to do this anytime
soon, but it can probably be rolled in eventually.

On Monday, August 31, 2015, jimboca <notifications@github.com> wrote:

> Would you be ok with loading the ISY notes and spoken properties so caller
> can reference nodes thru the spoken name? More info is here:
> http://forum.universal-devices.com/topic/16646-notes-field/?p=146578
>
> This would make it easier to reference the spoken name for my Amazon Echo
> interface in https://github.com/jimboca/ISYHelper
>
> Thanks,
> Jim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/automicus/PyISY/issues/9>.
>


-- 
Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
Thanks, I can look into adding it.

**Comment by jimboca** [comment]
Where would you prefer this code added?  Inside Nodes/__init__.py before inserting the new Node?  Since it will have to make a rest call on each individual node?

**Comment by rmkraus** [comment]
It is probably best if this information is parsed on the fly. It won't be changing often so it probably doesn't need to be monitored. It also doesn't alter the way nodes are addressed or handled so it doesn't really need to be cached. 

So, the REST call will live in the [Connection.py module](https://github.com/automicus/PyISY/blob/master/PyISY/Connection.py).

And then the [Nodes Class](https://github.com/automicus/PyISY/blob/master/PyISY/Nodes/node.py#L7) will need an extra method to return this information. There may also need to be a method in the [Group class](https://github.com/automicus/PyISY/blob/master/PyISY/Nodes/group.py#L4).

**Comment by jimboca** [comment]
Great, that's exactly what I am doing, I have it working just need to do more testing.   BTW, what is the best way to iterate over nodes?  I thought I understood the __iter__ and how it worked, but the only way I could get everything was this:
```
for child in isy.nodes.allLowerNodes:
    if child[0] is 'node':
        print child
        print isy.nodes[child[2]].spoken
```

**Comment by rmkraus** [comment]
Enhancement has been merged. Closing.
